import type { PatientRecord } from "./types";

export const samplePatients: PatientRecord[] = [
  {
    patientInfo: {
      id: "P-10241",
      name: "Ramesh Iyer",
      age: 58,
      sex: "Male",
      abhaId: "12-3456-7890-1234",
      language: "English",
    },
    arrivedAt: "09:12",
    urgency: "red-flag",
    reviewed: false,
    symptoms: [
      {
        question: "What brings you in today?",
        answer: "Heaviness in my chest since last night, it comes in waves.",
        at: "09:13",
      },
      {
        question: "You mentioned chest heaviness — does it spread to your arm, jaw or back?",
        answer: "Yes, down my left arm.",
        at: "09:14",
      },
      {
        question: "Are you sweating or feeling short of breath with it?",
        answer: "Sweating a lot, and breathless when I walk to the gate.",
        at: "09:15",
      },
      {
        question: "Have you taken your blood pressure medicine today?",
        answer: "No, I missed it yesterday and today.",
        at: "09:16",
      },
    ],
    history: [
      { condition: "Hypertension", since: "2016", status: "Active" },
      { condition: "Hyperlipidaemia", since: "2019", status: "Monitored" },
      { condition: "Smoker (15 pack-years)", since: "1998", status: "Active" },
    ],
    medications: [
      { name: "Telmisartan", dose: "40 mg", frequency: "Once daily" },
      { name: "Atorvastatin", dose: "20 mg", frequency: "At night" },
    ],
    reports: [
      {
        id: "R-771",
        title: "Lipid profile + ECG note",
        kind: "Lab report",
        uploadedAt: "09:17",
        fields: [
          { label: "LDL Cholesterol", value: "164 mg/dL", flagged: true, x: 62, y: 34 },
          { label: "Total Cholesterol", value: "248 mg/dL", flagged: true, x: 60, y: 48 },
          { label: "ECG note", value: "ST-T changes, lead II", flagged: true, x: 34, y: 68 },
          { label: "Collected on", value: "28 Aug 2026", x: 30, y: 20 },
        ],
      },
    ],
    timelineEvents: [
      {
        id: "t1",
        date: "2016",
        label: "Hypertension diagnosed",
        detail: "BP 158/96 at routine camp, started on amlodipine.",
        kind: "condition",
        severity: "medium",
      },
      {
        id: "t2",
        date: "2019",
        label: "Switched to Telmisartan",
        detail: "Ankle oedema on amlodipine, regimen changed.",
        kind: "treatment",
        severity: "low",
      },
      {
        id: "t3",
        date: "2023",
        label: "Lipids rising",
        detail: "LDL 152 mg/dL, statin dose increased to 20 mg.",
        kind: "lab",
        severity: "medium",
      },
      {
        id: "t4",
        date: "Aug 2026",
        label: "Missed doses reported",
        detail: "Two consecutive days of antihypertensive missed.",
        kind: "visit",
        severity: "medium",
      },
      {
        id: "t5",
        date: "Today",
        label: "Chest heaviness with radiation",
        detail: "Exertional, radiating to left arm, diaphoresis.",
        kind: "visit",
        severity: "high",
      },
    ],
    aiSummary: {
      chiefComplaint: "Episodic chest heaviness for ~14 hours, radiating to the left arm.",
      associatedSymptoms: ["Diaphoresis", "Exertional dyspnoea", "Nausea (mild)"],
      duration: "Since last night (~14 hours), waxing and waning",
      pastHistory: ["Hypertension since 2016", "Hyperlipidaemia", "Active smoker"],
      currentMedication: ["Telmisartan 40 mg OD (2 doses missed)", "Atorvastatin 20 mg HS"],
      oneLiner: "58M, hypertensive smoker with 14h radiating chest heaviness and diaphoresis.",
      confidence: 0.86,
    },
    redFlags: [
      {
        title: "Possible acute coronary syndrome pattern",
        trigger:
          "Chest pain + radiation to left arm + diaphoresis + exertional dyspnoea in a hypertensive smoker aged 58.",
        recommendation: "Prioritise for immediate physician review, ECG and troponin.",
      },
    ],
  },
  {
    patientInfo: {
      id: "P-10242",
      name: "Sunita Devi",
      age: 46,
      sex: "Female",
      abhaId: "45-7712-9032-8871",
      language: "Hindi",
    },
    arrivedAt: "09:26",
    urgency: "priority",
    reviewed: false,
    symptoms: [
      { question: "What brings you in today?", answer: "Fever for three days, feeling very weak.", at: "09:27" },
      {
        question: "You mentioned fever for 3 days — is it constant or does it come and go?",
        answer: "It comes in the evening, with chills.",
        at: "09:28",
      },
      {
        question: "Any burning while passing urine, or wound on your feet?",
        answer: "There is a small sore on my right foot, it is not healing.",
        at: "09:29",
      },
      {
        question: "Have you checked your sugar during the fever?",
        answer: "Yes, it was around 300 in the morning.",
        at: "09:30",
      },
    ],
    history: [
      { condition: "Type 2 diabetes mellitus", since: "2014", status: "Active" },
      { condition: "Diabetic neuropathy", since: "2022", status: "Monitored" },
    ],
    medications: [
      { name: "Metformin", dose: "1000 mg", frequency: "Twice daily" },
      { name: "Glimepiride", dose: "2 mg", frequency: "Morning" },
    ],
    reports: [
      {
        id: "R-772",
        title: "Fasting glucose & HbA1c",
        kind: "Lab report",
        uploadedAt: "09:31",
        fields: [
          { label: "Glucose (fasting)", value: "180 mg/dL", flagged: true, x: 58, y: 30 },
          { label: "HbA1c", value: "9.4 %", flagged: true, x: 58, y: 44 },
          { label: "Haemoglobin", value: "11.2 g/dL", x: 58, y: 58 },
          { label: "Lab", value: "City Diagnostics", x: 28, y: 16 },
        ],
      },
      {
        id: "R-773",
        title: "Prescription — Dr. Nair",
        kind: "Prescription",
        uploadedAt: "09:32",
        fields: [
          { label: "Metformin", value: "1000 mg BD", x: 40, y: 36 },
          { label: "Glimepiride", value: "2 mg OD", x: 40, y: 52 },
        ],
      },
    ],
    timelineEvents: [
      {
        id: "t1",
        date: "2014",
        label: "Type 2 diabetes diagnosed",
        detail: "HbA1c 8.1%, started metformin.",
        kind: "condition",
        severity: "medium",
      },
      {
        id: "t2",
        date: "2022",
        label: "Neuropathy noted",
        detail: "Reduced sensation in both feet on monofilament test.",
        kind: "condition",
        severity: "medium",
      },
      {
        id: "t3",
        date: "Mar 2026",
        label: "HbA1c 9.4%",
        detail: "Glimepiride added, diet counselling given.",
        kind: "lab",
        severity: "high",
      },
      {
        id: "t4",
        date: "Today",
        label: "3-day fever + non-healing foot sore",
        detail: "Evening spikes with chills, capillary glucose ~300 mg/dL.",
        kind: "visit",
        severity: "high",
      },
    ],
    aiSummary: {
      chiefComplaint: "Intermittent fever with chills for 3 days.",
      associatedSymptoms: ["Generalised weakness", "Non-healing sore on right foot", "High capillary glucose (~300)"],
      duration: "3 days, evening-predominant",
      pastHistory: ["T2DM since 2014, HbA1c 9.4%", "Diabetic neuropathy"],
      currentMedication: ["Metformin 1000 mg BD", "Glimepiride 2 mg OD"],
      oneLiner: "46F, poorly controlled T2DM with 3-day fever and a non-healing foot ulcer.",
      confidence: 0.82,
    },
    redFlags: [
      {
        title: "Possible diabetic foot infection with poor glycaemic control",
        trigger: "Fever ≥3 days + non-healing foot ulcer + capillary glucose ~300 mg/dL in known T2DM.",
        recommendation: "Prioritise wound inspection, glucose panel and infection markers.",
      },
    ],
  },
  {
    patientInfo: {
      id: "P-10243",
      name: "Arjun Menon",
      age: 27,
      sex: "Male",
      abhaId: "88-1200-4432-1090",
      language: "English",
    },
    arrivedAt: "09:41",
    urgency: "normal",
    reviewed: false,
    symptoms: [
      { question: "What brings you in today?", answer: "Sore throat and blocked nose since yesterday.", at: "09:42" },
      {
        question: "You mentioned a sore throat — any fever or difficulty swallowing?",
        answer: "Slight fever last night, swallowing is fine.",
        at: "09:43",
      },
      { question: "Any breathlessness or chest pain?", answer: "No.", at: "09:44" },
    ],
    history: [{ condition: "Allergic rhinitis", since: "2019", status: "Monitored" }],
    medications: [{ name: "Cetirizine", dose: "10 mg", frequency: "As needed" }],
    reports: [],
    timelineEvents: [
      {
        id: "t1",
        date: "2019",
        label: "Allergic rhinitis",
        detail: "Seasonal symptoms, responds to antihistamines.",
        kind: "condition",
        severity: "low",
      },
      {
        id: "t2",
        date: "Today",
        label: "Upper respiratory symptoms",
        detail: "Sore throat, nasal block, low-grade fever.",
        kind: "visit",
        severity: "low",
      },
    ],
    aiSummary: {
      chiefComplaint: "Sore throat with nasal congestion for 1 day.",
      associatedSymptoms: ["Low-grade fever", "No dysphagia", "No dyspnoea"],
      duration: "1 day",
      pastHistory: ["Allergic rhinitis since 2019"],
      currentMedication: ["Cetirizine 10 mg PRN"],
      oneLiner: "27M with 1-day sore throat and nasal congestion, no red flags.",
      confidence: 0.91,
    },
    redFlags: [],
  },
  {
    patientInfo: {
      id: "P-10244",
      name: "Fatima Sheikh",
      age: 67,
      sex: "Female",
      abhaId: "31-9087-2210-5567",
      language: "Urdu",
    },
    arrivedAt: "09:55",
    urgency: "priority",
    reviewed: true,
    symptoms: [
      { question: "What brings you in today?", answer: "Knee pain, worse on the stairs.", at: "09:56" },
      {
        question: "You mentioned knee pain — is it one knee or both?",
        answer: "Both, right one is worse.",
        at: "09:57",
      },
      { question: "Is there morning stiffness that lasts more than an hour?", answer: "About 20 minutes.", at: "09:58" },
    ],
    history: [
      { condition: "Osteoarthritis (knees)", since: "2018", status: "Active" },
      { condition: "Hypothyroidism", since: "2011", status: "Monitored" },
    ],
    medications: [
      { name: "Levothyroxine", dose: "50 mcg", frequency: "Morning, empty stomach" },
      { name: "Paracetamol", dose: "650 mg", frequency: "As needed" },
    ],
    reports: [
      {
        id: "R-774",
        title: "Knee X-ray report",
        kind: "Lab report",
        uploadedAt: "09:59",
        fields: [
          { label: "Findings", value: "Grade 3 medial joint space loss", flagged: true, x: 46, y: 40 },
          { label: "Impression", value: "Bilateral OA, right > left", x: 42, y: 60 },
        ],
      },
    ],
    timelineEvents: [
      {
        id: "t1",
        date: "2011",
        label: "Hypothyroidism",
        detail: "TSH 8.9, started levothyroxine.",
        kind: "condition",
        severity: "low",
      },
      {
        id: "t2",
        date: "2018",
        label: "Knee osteoarthritis",
        detail: "Physiotherapy and weight management advised.",
        kind: "condition",
        severity: "medium",
      },
      {
        id: "t3",
        date: "Today",
        label: "Worsening mechanical knee pain",
        detail: "Stair-related pain, 20 min morning stiffness.",
        kind: "visit",
        severity: "medium",
      },
    ],
    aiSummary: {
      chiefComplaint: "Bilateral knee pain, worse on stairs, right side dominant.",
      associatedSymptoms: ["Morning stiffness ~20 min", "No joint swelling reported"],
      duration: "Chronic, progressive over months",
      pastHistory: ["Knee osteoarthritis since 2018", "Hypothyroidism since 2011"],
      currentMedication: ["Levothyroxine 50 mcg OD", "Paracetamol 650 mg PRN"],
      oneLiner: "67F with progressive mechanical knee pain, radiographic grade 3 OA.",
      confidence: 0.88,
    },
    redFlags: [],
  },
];
